name: visitbj
description: A mobile app for booking touristic path
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider:
  shared_preferences:
  google_fonts:
  dio:
  flutter_svg:
  cached_network_image:
  flutter_screenutil:
  auto_size_text:
  animations:
  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
